import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Card from "@/components/card";

import coffeeStoresData from "../data/coffee-stores";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

const handleOnBannerBtnClick = () => console.log("click");

export default function Home({ coffeeStores }) {
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <Image
          className={styles.logo}
          src="/static/coffee.png"
          width={230}
          height={300}
          alt=""
          title="Illustration by Icons 8 from Ouch!"
        />
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map(({ id, imgUrl, name }, index) => (
                <Card
                  key={id}
                  name={name}
                  imgURL={imgUrl}
                  href={`coffee-store/${id}`}
                  className={styles.card}
                  last={index === coffeeStores.length - 1}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </>
  );
}
