import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";

import coffeeStoresData from "../data/coffee-stores";
import StoresGroup from "@/components/storesGroup";

export async function getStaticProps() {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

const handleOnBannerBtnClick = () => console.log("click");

export default function Home({ coffeeStores }) {
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <Image
          className={styles.logo}
          src="/static/coffee.png"
          width={230}
          height={300}
          alt=""
          title="Illustration by Icons 8 from Ouch!"
        />
        {coffeeStores.length > 0 && <StoresGroup coffeeStores={coffeeStores} />}
        {coffeeStores.length > 0 && <StoresGroup coffeeStores={coffeeStores} />}
        {coffeeStores.length > 0 && <StoresGroup coffeeStores={coffeeStores} />}
      </main>
    </>
  );
}
